### PR TITLE
add CLI for Pluto

### PR DESCRIPTION
**Pull request by Roger-luo**

### CODE REVIEW

**Comment by Roger-luo** [comment]
I think eventually as an option for speed up start up, we can ship a system image with the CLI like what I do for IonCLI. You can find the automated system image build here: https://github.com/Roger-luo/IonCLI.jl/releases

**Comment by fonsp** [comment]
Thanks!

I tried it today but it did not create the `~/.julia/bin` folder when I added PlutoUtils.

Here's my terminal history:
```
(v1.5) pkg>

**Comment by Roger-luo** [comment]
Hi @fonsp as for dev I believe you need to run build manually, since Julia won't build automatically in dev if the folder exists. 

]build PlutoUtils

**Comment by fonsp** [comment]
Thanks, that worked!

I found that `Ctrl+C` does not always work. If you run Pluto using the CLI, then open all 5 samples notebooks at once (by `Ctrl`+clicking them one by one), wait 10 seconds, and then `Ctrl+C`, then you see the message:

```
fons@woof:~/PlutoUtils.jl$ ~/.julia/bin/pluto
Go to http://localhost:1234/ to start writing ~ have fun!

Press Ctrl+C in this terminal to stop Pluto

^C
signal (2): Interrupt
in expression starting at /home/fons/.julia/bin/pluto.jl:1
epoll_pwait at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
uv__io_poll at /workspace/srcdir/libuv/src/unix/linux-core.c:270
uv_run at /workspace/srcdir/libuv/src/unix/core.c:359
jl_task_get_next at /buildworker/worker/package_linux64/build/src/partr.c:473
poptask at ./task.jl:704
wait at ./task.jl:712 [inlined]
wait at ./condition.jl:106
macro expansion at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Distributed/src/remotecall.jl:253 [inlined]
#133 at ./task.jl:356
jfptr_YY.133_57914.clone_1 at /home/fons/julia-1.5.0-rc1/lib/julia/sys.so (unknown line)
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2214 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2398
jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1690 [inlined]
start_task at /buildworker/worker/package_linux64/build/src/task.c:707
unknown function (ip: (nil))
unknown function (ip: (nil))
Allocations: 2543 (Pool: 2533; Big: 10); GC: 0

fons@woof:~/PlutoUtils.jl$
```

But the notebooks are still running (you can change code).

Maybe this is my fault - there is some improvised code to listen for `Ctrl+C`: https://github.com/fonsp/Pluto.jl/blob/master/src/webserver/WebServer.jl#L232-L236
I remember having lots of trouble with this. The three commands:
```
julia -e "import Pluto; Pluto.run()"
```
```
julia <<__EOF__
import Pluto
Pluto.run()
__EOF__
```
and
```
julia a_script_that_does_that.jl
```

handle `Ctrl+C` in three different ways 😢

**Comment by fonsp** [comment]
The difference lies in the way Julia handles `Ctrl+C`: if you are in interactive mode (ie the REPL), then `Ctrl+C` sends an `InterruptException` to the code that is currently running. In normal mode (ie when you run a `.jl` file), the program terminates immediately. This means that Pluto can't clean up the notebook processes and the HTTP server. 

For example, if you run
```julia
try
    println("Press Ctrl+C to stop me")
    sleep(60)
catch e
    @info "Caught" e
    @show e isa InterruptException
end
```

in your terminal, then you see `Caught`. If you save it as `hello.jl` and run `julia hello.jl`, then you see a segfaulty message. 

There is no command line switch for Julia to change this behaviour - it needs to be done using `ccall`:

```julia
ccall(:jl_exit_on_sigint, Cvoid, (Cint,), 0)

try
    println("Press Ctrl+C to stop me")
    sleep(60)
catch e
    @info "Caught" e
    @show e isa InterruptException
end
```

If you save this as a file and run it, then it works!

We could add that line inside the `main` function, or if you think it is appropriate, it could be added to Comonicon.

**Comment by Roger-luo** [comment]
Ah, yeah I actually also spot this, but somehow after it segment fault a few times on my Mac, Pluto can exit correctly...

Yeah, this should be in Comonicon, since I believe all other CLI will have the same problem.

**Comment by Roger-luo** [comment]
I just released a patch for Comonicon, this should be fixed once this patch version gets merged in General!

**Comment by Roger-luo** [comment]
Comonicon can actually install the path for you, so user won't need to export `PATH` manually. But Julia's `Pkg.build` disabled all interactive mode, thus I cannot prompt to ask about whether the user want it.

but currently one can do this manually by

```julia
using Comonicon.BuildTools; BuildTools.install_env_path()
```

this will install both `PATH` and `FPATH` for auto-completion if it's in ZSH. I added one line in README to mention this for now, until we figure out a more automatic way to install `PATH`.

**Comment by fonsp** [comment]
Oh that's very cool! Can that be inside a function `PlutoUtils.add_pluto_cli()`?

**Comment by Roger-luo** [comment]
yeah I could add this in Comonicon, currently since the system image build is not very reliable, I provide an option that one can always build things locally via something like `PlutoUtils.comonicon_build`, I guess I could just generate this from Comonicon side, e.g `PlutoUtils.comonicon_install()`

**Pull request merged**
