### PR TITLE
support open notebook & local environment

### PR DESCRIPTION
**Pull request by Roger-luo**
this implements #7 requires https://github.com/fonsp/Pluto.jl/pull/341

### CODE REVIEW

**Comment by Roger-luo** [comment]
I updated the version, since in Comonicon's convention (also Julia's, I think) the first version starts from v0.1.0

**Comment by fonsp** [comment]
Thanks a lot! I'll have a look at the Pluto PR

**Comment by fonsp** [comment]
Feel free to merge this when you're happy

**Comment by Roger-luo** [comment]
Cool, I'll merge this first, and probably I think it's time to tag the first version to make this more accessible.

**Comment by Roger-luo** [comment]
Yeah, I think I'll try to finish the other environment variable PR before your next release, since that along with the per notebook environment PR should be in a minor version. 

I also just realize tho the feature seems right, but the fallbacks seems not (not falling back to `@.` but global one if notebook environment not specified but run with --project flag). I will need to adjust this a bit here.

**Pull request merged**
