### PR TITLE
Fixed Docker Volume permissions

### PR DESCRIPTION
**Pull request by lungben**
See https://github.com/fonsp/PlutoUtils.jl/issues/5

Furthermore, I added a docker-compose.yaml file, with that (at least for me) the volume works correctly.

### CODE REVIEW

**Comment by lungben** [comment]
This works on Windows, but not on Linux. Still checking it.

**Comment by lungben** [comment]
Now it is working for me.
On Linux, you have to do the following on your host machine before starting the container:

`
mkdir notebooks
chown -R 1000:1000 notebooks
docker-compose up -d
`

Unfortunately it is required to create the monted volume on the host directory and to transfer ownership to the user ID in the container due to a Docker limitation (see https://github.com/moby/moby/issues/2259).

For Windows, these steps are not required.

**Comment by fonsp** [comment]
I gave you access to merge this (and future PRs) yourself!

**Comment by lungben** [comment]
Thanks!
The docker image is already updated.

**Pull request merged**
